apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: rsv-gen2
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  # Para acesso externo, altere para NodePort ou LoadBalancer
  # type: NodePort
  # type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: prometheus
    component: monitoring
  sessionAffinity: None

