apiVersion: v1
kind: Service
metadata:
  name: rsv-gen2-app-service
  namespace: rsv-gen2
  labels:
    app: rsv-gen2
    component: app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rsv-gen2
    component: app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  name: rsv-gen2-websocket-service
  namespace: rsv-gen2
  labels:
    app: rsv-gen2
    component: websocket
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: ws
  selector:
    app: rsv-gen2
    component: websocket
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

