apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: rsv-gen2
  labels:
    app: alertmanager
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: web
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: cluster
  selector:
    app: alertmanager
    component: monitoring
  sessionAffinity: None

